website/auth.py
from crypt import methods
from unicodedata import category
from flask import Blueprint,render_template, redirect, url_for , request, flash
from . import db
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth',__name__)

@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method=='POST':
        email =  request.form.get('email')
        password =  request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password,password):
                flash('Logged In Successfully', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Invalid Email or Password', category='error')
        else:
            flash('Invalid Email or Password', category='error')
    return render_template('login.html',user=current_user)

@auth.route('/sign-up', methods=['GET','POST'])
def sign_up():
    if request.method=='POST':
        email =  request.form.get('email')
        username =  request.form.get('username')
        password1 =  request.form.get('password1')
        password2 =  request.form.get('password2')

        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()
        if email_exists:
            flash('Email is already taken.',  category='error')
        elif username_exists:
            flash('Username is already taken.',  category='error')
        elif password1!=password2:
            flash('Passwords are different', category='error')
        elif len(username)<3:
            flash('Username should be minimun 3 chars long', category='error')
        elif len(password1)<6:
            flash('Password should be minimun 6 chars long', category='error')
        else:
            hashed_password =  generate_password_hash(password1, method='sha256')
            new_user = User(email=email,username=username,password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            flash('Account Created')
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))
        

    return render_template('signup.html',user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/home">Home</a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="/logout">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="/login">Login</a>
                <a class="nav-item nav-link" href='{{ url_for("auth.sign_up") }}'>Sign Up</a>
            {% endif %}
              
              
            </div>
          </div>
        </div>
      </nav>
      {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %} 
      {% for category, message in messages %} 
      {% if category == 'error' %}
        <div class="alert alert-danger alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}
        <div class="container">{% block content %}{% endblock %}</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</html>

website/templates/create_post.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<h1 align="center">Make a Post</h1>

<form method="POST">
  <textarea name="text" id="text" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-lg btn-primary">Post</button>
  </div>
</form>
<br />
<div align="center">
  <a href="/home"
    ><button type="button" class="btn btn-lg btn-secondary">Back</button></a
  >
</div>
{% endblock %}

website/templates/home.html
{% extends "posts_div.html" %} {% block title %}Home{% endblock %}

website/templates/login.html
{% extends "base.html" %} 
{% block title %}Login{% endblock %} 
{% block content%}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
    <label for="email">Email Address</label>
    <input
        type="text"
        id="email"
        name="email"
        class="form-control"
        placeholder="Enter Email"
    />
    <label for="password">Password</label>
    <input
        type="password"
        id="password"
        name="password"
        class="form-control"
        placeholder="Enter Password"
    />
    <br />
    <div align="center">
        <button class="btn btn-primary" type="submit">Login</button>
    </div>
    </div>
</form>
{% endblock %}

website/templates/posts.html
{% extends "posts_div.html" %} {% block title %}{{username}}'s Posts{% endblock
    %} {% block header %} {{user.username}}'s posts {% endblock %} {% block footer %}
    <div align="center">
      <a href="/home"
        ><button type="button" class="btn btn-primary btn-lg">Back</button></a
      >
    </div>
{% endblock %}

website/templates/posts_div.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
  %}
  <h1 align="center">{% block header %}Posts{% endblock %}</h1>
  <div id="posts">
    {% for post in posts %}
    <div class="card border-dark">
      <div class="card-header d-flex justify-content-between align-items-center">
        <a href="/posts/{{post.user.username}}">{{post.user.username}}</a>
        {% if user.id in post.likes|map(attribute="author")|list %}
        <i
          class="fas fa-thumbs-up"
          id="like-button-{{post.id}}"
        ></i>
        {% else %}
        <i
          class="far fa-thumbs-up"
          id="like-button-{{post.id}}"
        ></i>
        {% endif %}
        {% if user.id == post.author %}
        <div class="btn-group">
          <button
            type="button"
            class="btn btn-sm btn-primary dropdown-toggle"
            data-bs-toggle="dropdown"
          ></button>
          <ul class="dropdown-menu">
            <li>
              <a href="/update-post/{{post.id}}" class="dropdown-item">Update</a>
            </li>
            <li>
              <a href="/delete-post/{{post.id}}" class="dropdown-item">Delete</a>
            </li>

          </ul>
        </div>
        {% endif %}
      </div>
      <div class="card-body">
        <div class="card-text">{{post.text}}</div>
        <br />
        <div class="collapse" id="comments-{{post.id}}">
          <div class="card">
            <div class="card-body" id="comments-expanded-{{post.id}}">
              {% for comment in post.comments %}
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <a href="/posts/{{comment.user.username}}"
                    >{{comment.user.username}}</a
                  >: {{comment.text}}
                </div>
                <div>
                  <small class="text-muted"> {{comment.date_created}}</small>
                  {% if user.id == comment.author or user.id == post.author %}
                  <div class="btn-group">
                    <button
                      type="button"
                      class="btn btn-sm btn-primary dropdown-toggle"
                      data-bs-toggle="dropdown"
                    ></button>
                    <ul class="dropdown-menu">
                      <li>
                        <a
                          href="/delete-comment/{{comment.id}}"
                          class="dropdown-item"
                          >Delete</a
                        >
                      </li>
                    </ul>
                  </div>
                  {% endif %}
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <p class="card-text">
          {% if post.comments|length > 0 %}
          <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
            <small>View {{post.comments|length}} Comments</small>
          </a>
          {% else %}
          <small class="text-muted">No Comments</small>
          {% endif %}
        </p>
        <form
          class="input-group mb-3"
          method="POST"
          action="/create-comment/{{post.id}}"
        >
          <input
            type="text"
            id="text"
            name="text"
            class="form-control"
            placeholder="Comment something!"
          />
          <button type="submit" class="btn btn-primary">Comment</button>
        </form>
      </div>
      <div class="card-footer text-muted">{{post.date_created}}</div>
    </div>
    <br/ > {% endfor %}
  </div>
  {% block footer %}
  <div align="center">
    <a href="/create-post"
      ><button type="button" class="btn btn-primary btn-lg">
        Create a Post
      </button></a
    >
  </div>
  {% endblock %} {% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}

{% block content %}
<form method="POST">
    <h3 class="align"></h3>
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
    <label for="email">Email Address</label>
    <input
        type="email"
        id="email"
        name="email"
        class="form-control"
        placeholder="Enter Email"
        required="True"
    />
    <label for="username">Username</label>
    <input
        type="text"
        id="username"
        name="username"
        class="form-control"
        placeholder="Enter Username"
    />
    <label for="password1">Password</label>
    <input
        type="password"
        id="password1"
        name="password1"
        class="form-control"
        placeholder="Enter Password"
    />
    <label for="password2">Password Again</label>
    <input
        type="password"
        id="password2"
        name="password2"
        class="form-control"
        placeholder="Enter Password Again"
    />
    <br />
    <div align="center">
        <button class="btn btn-primary" type="submit">Sign Up</button>
    </div>
    </div>
</form>

{% endblock %}

website/templates/update_post.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<h1 align="center">Update a Post</h1>

<form method="POST">
  <textarea name="text" id="text" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-lg btn-primary">Update Post</button>
  </div>
</form>
<br />
<div align="center">
  <a href="/home"
    ><button type="button" class="btn btn-lg btn-secondary">Back</button></a
  >
</div>
{% endblock %}